// Copyright 2023-2024 - Roberto De Ioris.


#include "CompushadySyntaxHighlighter.h"
#include "Runtime/Slate/Public/Framework/Text/IRun.h"
#include "Runtime/Slate/Public/Framework/Text/TextLayout.h"
#include "Runtime/Slate/Public/Framework/Text/SlateTextRun.h"


TSharedRef<FCompushadySyntaxHighlighter> FCompushadySyntaxHighlighter::CreateGLSL()
{

	// https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.html

	COMPUSHADY_SH_BEGIN;

	// basic types
	COMPUSHADY_SH_ADD_TYPE_RULE("bool");
	COMPUSHADY_SH_ADD_TYPE_RULE("bvec2");
	COMPUSHADY_SH_ADD_TYPE_RULE("bvec3");
	COMPUSHADY_SH_ADD_TYPE_RULE("bvec4");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat2");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat2x2");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat2x3");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat2x4");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat3");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat3x2");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat3x3");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat3x4");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat4");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat4x2");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat4x3");
	COMPUSHADY_SH_ADD_TYPE_RULE("dmat4x4");
	COMPUSHADY_SH_ADD_TYPE_RULE("double");
	COMPUSHADY_SH_ADD_TYPE_RULE("dvec2");
	COMPUSHADY_SH_ADD_TYPE_RULE("dvec3");
	COMPUSHADY_SH_ADD_TYPE_RULE("dvec4");
	COMPUSHADY_SH_ADD_TYPE_RULE("float");
	COMPUSHADY_SH_ADD_TYPE_RULE("int");
	COMPUSHADY_SH_ADD_TYPE_RULE("ivec2");
	COMPUSHADY_SH_ADD_TYPE_RULE("ivec3");
	COMPUSHADY_SH_ADD_TYPE_RULE("ivec4");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat2");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat2x2");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat2x3");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat2x4");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat3");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat3x2");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat3x3");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat3x4");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat4");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat4x2");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat4x3");
	COMPUSHADY_SH_ADD_TYPE_RULE("mat4x4");
	COMPUSHADY_SH_ADD_TYPE_RULE("uint");
	COMPUSHADY_SH_ADD_TYPE_RULE("uvec2");
	COMPUSHADY_SH_ADD_TYPE_RULE("uvec3");
	COMPUSHADY_SH_ADD_TYPE_RULE("uvec4");
	COMPUSHADY_SH_ADD_TYPE_RULE("vec2");
	COMPUSHADY_SH_ADD_TYPE_RULE("vec3");
	COMPUSHADY_SH_ADD_TYPE_RULE("vec4");
	COMPUSHADY_SH_ADD_TYPE_RULE("void");

	// opaque types
	COMPUSHADY_SH_ADD_TYPE_RULE("atomic_uint");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimage1D");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimage1DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimage2D");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimage2DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimage2DMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimage2DMSArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimage2DRect");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimage3D");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimageBuffer");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimageCube");
	COMPUSHADY_SH_ADD_TYPE_RULE("iimageCubeArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("image1D");
	COMPUSHADY_SH_ADD_TYPE_RULE("image1DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("image2D");
	COMPUSHADY_SH_ADD_TYPE_RULE("image2DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("image2DMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("image2DMSArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("image2DRect");
	COMPUSHADY_SH_ADD_TYPE_RULE("image3D");
	COMPUSHADY_SH_ADD_TYPE_RULE("imageBuffer");
	COMPUSHADY_SH_ADD_TYPE_RULE("imageCube");
	COMPUSHADY_SH_ADD_TYPE_RULE("imageCubeArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("isampler1D");
	COMPUSHADY_SH_ADD_TYPE_RULE("isampler1DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("isampler2D");
	COMPUSHADY_SH_ADD_TYPE_RULE("isampler2DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("isampler2DMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("isampler2DMSArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("isampler2DRect");
	COMPUSHADY_SH_ADD_TYPE_RULE("isampler3D");
	COMPUSHADY_SH_ADD_TYPE_RULE("isamplerBuffer");
	COMPUSHADY_SH_ADD_TYPE_RULE("isamplerCube");
	COMPUSHADY_SH_ADD_TYPE_RULE("isamplerCubeArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("isubpassInput");
	COMPUSHADY_SH_ADD_TYPE_RULE("isubpassInputMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("itexture1D");
	COMPUSHADY_SH_ADD_TYPE_RULE("itexture1DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("itexture2D");
	COMPUSHADY_SH_ADD_TYPE_RULE("itexture2DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("itexture2DMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("itexture2DMSArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("itexture2DRect");
	COMPUSHADY_SH_ADD_TYPE_RULE("itexture3D");
	COMPUSHADY_SH_ADD_TYPE_RULE("itextureBuffer");
	COMPUSHADY_SH_ADD_TYPE_RULE("itextureCube");
	COMPUSHADY_SH_ADD_TYPE_RULE("itextureCubeArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler1D");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler1DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler1DArrayShadow");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler1DShadow");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler2D");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler2DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler2DArrayShadow");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler2DMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler2DMSArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler2DRect");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler2DRectShadow");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler2DShadow");
	COMPUSHADY_SH_ADD_TYPE_RULE("sampler3D");
	COMPUSHADY_SH_ADD_TYPE_RULE("samplerBuffer");
	COMPUSHADY_SH_ADD_TYPE_RULE("samplerCube");
	COMPUSHADY_SH_ADD_TYPE_RULE("samplerCubeArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("samplerCubeArrayShadow");
	COMPUSHADY_SH_ADD_TYPE_RULE("samplerCubeShadow");
	COMPUSHADY_SH_ADD_TYPE_RULE("samplerShadow");
	COMPUSHADY_SH_ADD_TYPE_RULE("subpassInput");
	COMPUSHADY_SH_ADD_TYPE_RULE("subpassInputMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("texture1D");
	COMPUSHADY_SH_ADD_TYPE_RULE("texture1DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("texture2D");
	COMPUSHADY_SH_ADD_TYPE_RULE("texture2DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("texture2DMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("texture2DMSArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("texture2DRect");
	COMPUSHADY_SH_ADD_TYPE_RULE("texture3D");
	COMPUSHADY_SH_ADD_TYPE_RULE("textureBuffer");
	COMPUSHADY_SH_ADD_TYPE_RULE("textureCube");
	COMPUSHADY_SH_ADD_TYPE_RULE("textureCubeArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimage1D");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimage1DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimage2D");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimage2DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimage2DMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimage2DMSArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimage2DRect");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimage3D");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimageBuffer");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimageCube");
	COMPUSHADY_SH_ADD_TYPE_RULE("uimageCubeArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("usampler1D");
	COMPUSHADY_SH_ADD_TYPE_RULE("usampler1DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("usampler2D");
	COMPUSHADY_SH_ADD_TYPE_RULE("usampler2DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("usampler2DMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("usampler2DMSArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("usampler2DRect");
	COMPUSHADY_SH_ADD_TYPE_RULE("usampler3D");
	COMPUSHADY_SH_ADD_TYPE_RULE("usamplerBuffer");
	COMPUSHADY_SH_ADD_TYPE_RULE("usamplerCube");
	COMPUSHADY_SH_ADD_TYPE_RULE("usamplerCubeArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("usubpassInput");
	COMPUSHADY_SH_ADD_TYPE_RULE("usubpassInputMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("utexture1D");
	COMPUSHADY_SH_ADD_TYPE_RULE("utexture1DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("utexture1DArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("utexture2D");
	COMPUSHADY_SH_ADD_TYPE_RULE("utexture2DMS");
	COMPUSHADY_SH_ADD_TYPE_RULE("utexture2DMSArray");
	COMPUSHADY_SH_ADD_TYPE_RULE("utexture2DRect");
	COMPUSHADY_SH_ADD_TYPE_RULE("utexture3D");
	COMPUSHADY_SH_ADD_TYPE_RULE("utextureBuffer");
	COMPUSHADY_SH_ADD_TYPE_RULE("utextureCube");
	COMPUSHADY_SH_ADD_TYPE_RULE("utextureCubeArray");

	//keywords
	COMPUSHADY_SH_ADD_KEYWORD_RULE("if");
	COMPUSHADY_SH_ADD_KEYWORD_RULE("else");
	COMPUSHADY_SH_ADD_KEYWORD_RULE("for");
	COMPUSHADY_SH_ADD_KEYWORD_RULE("while");
	COMPUSHADY_SH_ADD_KEYWORD_RULE("return");



	// preprocessor
	COMPUSHADY_SH_ADD_PREPROCESSOR_RULE("#define");
	COMPUSHADY_SH_ADD_PREPROCESSOR_RULE("#version");

	// intrinsics

	COMPUSHADY_SH_ADD_INTRINSIC_RULE("abs");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("sign");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("floor");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("trunc");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("round");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("roundEven");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("ceil");

	COMPUSHADY_SH_ADD_KEYWORD_RULE("length");
	COMPUSHADY_SH_ADD_KEYWORD_RULE("distance");
	COMPUSHADY_SH_ADD_KEYWORD_RULE("dot");
	COMPUSHADY_SH_ADD_KEYWORD_RULE("normalize");
	COMPUSHADY_SH_ADD_KEYWORD_RULE("reflect");

	COMPUSHADY_SH_ADD_INTRINSIC_RULE("radians");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("degrees");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("sin");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("cos");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("tan");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("asin");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("acos");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("atan");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("sinh");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("cosh");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("tanh");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("asinh");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("acosh");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("atanh");

	COMPUSHADY_SH_ADD_INTRINSIC_RULE("texture");
	COMPUSHADY_SH_ADD_INTRINSIC_RULE("textureSize");

	// semantics
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_VertexIndex");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_InstanceIndex");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_InvocationID");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_PatchVerticesIn");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_PrimitiveIDIn");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_PrimitiveID");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_TessCoord");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_Layer");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_ViewportIndex");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_TessLevelOuter");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_TessLevelInner");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_NumWorkGroups");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_WorkGroupSize");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_WorkGroupID");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_LocalInvocationID");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_GlobalInvocationID");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_LocalInvocationIndex");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_FragCoord");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_FrontFacing");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_ClipDistance");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_CullDistance");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_PointCoord");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_SampleID");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_SamplePosition");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_HelperInvocation");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_FragDepth");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_SampleMaskIn");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_SampleMask");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_Position");
	COMPUSHADY_SH_ADD_SEMANTIC_RULE("gl_PointSize");

	// attributes
	COMPUSHADY_SH_ADD_ATTRIBUTE_RULE("const");
	COMPUSHADY_SH_ADD_ATTRIBUTE_RULE("in");
	COMPUSHADY_SH_ADD_ATTRIBUTE_RULE("out");
	COMPUSHADY_SH_ADD_ATTRIBUTE_RULE("layout");
	COMPUSHADY_SH_ADD_ATTRIBUTE_RULE("lowp");
	COMPUSHADY_SH_ADD_ATTRIBUTE_RULE("mediump");
	COMPUSHADY_SH_ADD_ATTRIBUTE_RULE("highp");
	COMPUSHADY_SH_ADD_ATTRIBUTE_RULE("std140");
	COMPUSHADY_SH_ADD_ATTRIBUTE_RULE("std430");
	COMPUSHADY_SH_ADD_ATTRIBUTE_RULE("uniform");

	// comments
	COMPUSHADY_SH_ADD_OPEN_COMMENT_RULE("/*");
	COMPUSHADY_SH_ADD_CLOSE_COMMENT_RULE("*/");
	COMPUSHADY_SH_ADD_LINE_COMMENT_RULE("//");

	// strings
	COMPUSHADY_SH_ADD_STRING_RULE("\"");

	COMPUSHADY_SH_END;
}